# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.vm.box = "perk/ubuntu-2204-arm64"
  config.vm.box = "boxen/ubuntu-22.04-x86_64"

  config.vm.provider "qemu" do |qe|
    qe.qemu_dir = "/opt/local/share/qemu"
    qe.arch = "x86_64"
    qe.machine = "q35"
    qe.cpu = "qemu64"
    qe.net_device = "virtio-net-pci"
  end

  # NOTE: Documentation for the qemu provider is available at
  # https://github.com/ppggff/vagrant-qemu

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
