# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.network "forwarded_port", guest: 443, host: 8443

  # config.vm.synced_folder "./", "/vagrant"

  config.vm.provider "utm" do |u|
    u.memory = 2048
    u.cpus = 2
  end
  config.vm.provision "shell", path: "01-apt-get-update.sh"
  config.vm.provision "shell", path: "02-apt-get-install-python3.sh"
  config.vm.provision "shell", path: "03-apt-get-install-redis.sh"
  config.vm.provision "shell", path: "04-apt-get-install-git.sh"
  config.vm.provision "shell", path: "05-apt-get-install-mysql.sh"
  config.vm.provision "shell", path: "06-create-mysql-database.sh"
  config.vm.provision "shell", path: "install_nautobot.sh"
end
