version: '3'
services:
  server-node01:
    # network_mode: "host"
    networks:
      consul_net:
        aliases:
          - consul-01
        ipv4_address: 172.22.0.10
    image: 'consul'
    environment:
      CONSUL_LOCAL_CONFIG: '{"server": true, "bootstrap_expect": 3}'
      CONSUL_CLIENT_INTERFACE: 'eth0'
      CONSUL_BIND_INTERFACE: 'eth0'
    command: ["agent", "-server"]
  server-node02:
    # network_mode: "host"
    networks:
      consul_net:
        aliases:
          - consul-02
        ipv4_address: 172.22.0.11
    image: 'consul'
    environment:
      # CONSUL_LOCAL_CONFIG: '{"server": true, "bootstrap_expect": 3, "start_join": ["172.22.0.10", "172.22.0.11", "172.22.0.12"]}'
      CONSUL_LOCAL_CONFIG: '{"server": true, "bootstrap_expect": 3, "start_join": ["consul-01", "consul-02", "consul-03"]}'
      CONSUL_CLIENT_INTERFACE: 'eth0'
      CONSUL_BIND_INTERFACE: 'eth0'
    command: ["agent", "-server"]
  server-node03:
    # network_mode: "host"
    networks:
      consul_net:
        aliases:
          - consul-03
        ipv4_address: 172.22.0.12
    image: 'consul'
    environment:
      # CONSUL_LOCAL_CONFIG: '{"server": true, "bootstrap_expect": 3, "start_join": ["172.22.0.10", "172.22.0.11", "172.22.0.12"]}'
      CONSUL_LOCAL_CONFIG: '{"server": true, "bootstrap_expect": 3, "start_join": ["consul-01", "consul-02", "consul-03"]}'
      CONSUL_CLIENT_INTERFACE: 'eth0'
      CONSUL_BIND_INTERFACE: 'eth0'
    command: ["agent", "-server"]

networks:
  consul_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.22.0.0/24
